<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Inicio',
    'About Us' => 'Nosotros',
    'Product' => 'Productos',
    'PTZ Camera' => 'Camaras PTZ',
    'Cameras' => 'Camaras',
    'Controls' => 'Controles',
    'How Works' => 'Como Funciona',
    'Contact Us' => 'Contactanos',
    'Purchace List' => 'Lista para enviar',
    '(empty)' => '(vacio)',
    'Contact us today.' => 'Contactenos hoy.',
    'We\'ll help you to find the best price.' => 'Lo ayudaremos a obtener el mejor precio.',
    'Free Quote' => 'Gratis',
    'Hours: 8am-5pm  M-Fr' => 'Horas: 8am-5pm  Lu-Vi',
    'Send' => 'Enviar',
    'Quick Links' => 'Atajos',
    'Follow Us' => 'Siguenos',
    'Customers' => 'Clientes',
    'Featured Products' => 'Productos Destacados',
    'Record with us Products' => 'Grava con nuestros Productos',
    'Where we are?' => '¿Donde Estamos?',
    'Your eyes when you are not there, choose modern technology with us.' => 'Tus ojos cuando no estas ahí, escoja la mas morderna tecnologia con nosotros',
    'Quick to install / Maximum quality / Competitive prices.' => 'Rapida instalacion / Maxima Calidad / Precios Competitivos.',
    'Make possible to monitor large areas with a single security camera.' => 'Haz posible poder monitoriar largas areas com una sola camara de seguridad.',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. Nosotros le responderemos lo antes posible.',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Si tiene preguntas de negocios u otras preguntas, por favor llene el siguiente formulario para contactarnos. Gracias.',
    'Full Name' => 'Nombre completo',
    'Email Address' => 'Correo electrónico',
    'Message:' => 'Mensage:',
    'Our Team' => 'Nuestro Equipo',
    'Management Department.' => 'Jefe de Departmento.',
    'Sales Representative.' => 'Representante de Ventas',
    'Technical Support.' => 'Soporte Técnico',
    'Products' => 'Productos',
    'Full Description ' => 'Descripcion completa',
    'Related Products' => 'Productos Similaers',
    'Add to List' => 'Añadir a la Lista',
    'Details' => 'Detalles',
    'Customer Name' => 'Nombre del Cliente',
    'Address' => 'Direccion',
    'Company' => 'Compañia',
    'Phone' => 'Telefono',
    'Email' => 'Correo',
    'Product Name' => 'Nombre del Producto',
    'Code' => 'Codigo',
    'Description' => 'Descripcion',
    'Image' => 'Imagen',
    'Purchase List' => 'Lista de Productos',
    'Create Purchase' => 'Crear Presupuesto',
    'Image' => 'Imagen',


];
