-- MySQL Script generated by MySQL Workbench
-- 06/24/17 18:17:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema halsecavision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema halsecavision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `halsecavision` DEFAULT CHARACTER SET utf8 ;
USE `halsecavision` ;

-- -----------------------------------------------------
-- Table `halsecavision`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `halsecavision`.`category` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `category_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `halsecavision`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `halsecavision`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `halsecavision`.`product` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(255) NULL,
  `qty_store` INT(11) NULL,
  `price` FLOAT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `fk_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `halsecavision`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `halsecavision`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `halsecavision`.`purchase` (
  `id` INT(11) NOT NULL,
  `qty` INT(11) NOT NULL DEFAULT 1,
  `customer_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `phone` INT(11) NOT NULL,
  `email` VARCHAR(45) NULL,
  `purchasecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `halsecavision`.`product_has_purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `halsecavision`.`product_has_purchase` (
  `product_id` INT(11) NOT NULL,
  `purchase_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `purchase_id`),
  INDEX `fk_product_has_purchase_purchase1_idx` (`purchase_id` ASC),
  INDEX `fk_product_has_purchase_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_purchase_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `halsecavision`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_purchase_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `halsecavision`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
